### ISSUE TITLE
Trying to run FoodTruck

### ISSUE THREAD

**Issue by thhgcn** [ludovicchabant/PieCrust2#29]
I was trying to run the FoodTruck admin panel by my own, since there is no specific instruction to do that. 

I created a new site using `chef init`, then run `chef admin init` and `chef admin run`. I could hit the login page and put the admin user and password, but after that I only got an Internal Server Error. There is any other action I need to take to run the admin panel? 

```
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Jan/2016 22:36:32] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [28/Jan/2016 22:36:32] "GET /login?next=%2F HTTP/1.1" 200 -
127.0.0.1 - - [28/Jan/2016 22:36:32] "GET /static/css/foodtruck.min.css HTTP/1.1" 404 -
127.0.0.1 - - [28/Jan/2016 22:36:32] "GET /static/js/foodtruck.min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Jan/2016 22:36:36] "POST /login?next=%2F HTTP/1.1" 302 -
Exception on / [GET]
Traceback (most recent call last):
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/foodtruck/views/main.py", line 24, in index
    site = g.sites.get(site_name)
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/foodtruck/sites.py", line 132, in get
    root_dir = self.get_root_dir(name)
  File "/home/thhg/workspace/piecrust/env/lib/python3.5/site-packages/foodtruck/sites.py", line 118, in get_root_dir
    root_dir = scfg.get('path')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ludovicchabant** [comment]
He he yeah, well, I'm not sure why I pushed this code already, since it's still firmly into the "work in progress" stage :)

What happens is that you need to add more stuff to the `foodtruck.yml` configuration file to point to the websites you want to manage, but I'm not going to tell you since, between the version you have and the version I'll push soon, I completely changed how the configuration file works anyway! So sit tight, it should only be a few more days until it gets official :)

**Comment by ludovicchabant** [comment]
Taking longer than I thought because of problems managing sub-processes... :(

The latest pushed code will let you run `chef admin run` directly inside your website and give the admin panel a try, though! As for publish targets, it's now using what I think will be the final design, so you would add something like this to your `config.yml`:

```
publish:
    my_test_target:
        type: shell
        cmd: "some command to run"
```

Right now only `shell` publish targets are supported.

**Comment by thhgcn** [comment]
Thanks for your work, man.

When trying the admin panel, I got this:

```
An Error Occured

The was an error with your configuration file: No sites are defined in the configuration file.
```

Is it necessary to declare the sites in foodtruck.yml? What is the pattern?

**Comment by ludovicchabant** [comment]
You shouldn't need any `foodtruck.yml` if you run `chef admin run` from inside your website... having such a file is probably upsetting it, so just delete it and try again?
