### ISSUE TITLE
Textile formatter causes "Unknown locale: UTF-8" on OSX

### ISSUE THREAD

**Issue by Lia-Sae** [ludovicchabant/PieCrust2#3]
When running chef with latest on OSX (virtual env enabled), it only prints "Unknown locale: UTF-8".
This is due to OSX (faultily?) putting UTF-8 in the LC_CTYPE environment variable and is apparently widespread with Python programs.

The version in pip is not affected. 
Workarounds:
- Removing the textile import statement in piecrust/plugins/builtin.py (verified)
- Setting LC_CTYPE to another value in .bash_profile or similar (non verified)

Stacktrace:
[piecrust.main] unknown locale: UTF-8
Traceback (most recent call last):
  File ".../PieCrust2/piecrust/main.py", line 58, in main
    exit_code = _run_chef(pre_args)
  File ".../PieCrust2/piecrust/main.py", line 182, in _run_chef
    commands = sorted(app.plugin_loader.getCommands(),
  File ".../PieCrust2/piecrust/plugins/base.py", line 75, in getCommands
    return self._getPluginComponents('getCommands')
  File ".../PieCrust2/piecrust/plugins/base.py", line 113, in _getPluginComponents
    for plugin in self.plugins:
  File ".../PieCrust2/piecrust/plugins/base.py", line 51, in plugins
    self._ensureLoaded()
  File ".../PieCrust2/piecrust/plugins/base.py", line 93, in _ensureLoaded
    from piecrust.plugins.builtin import BuiltInPlugin
  File ".../PieCrust2/piecrust/plugins/builtin.py", line 16, in <module>
from piecrust.commands.base import HelpCommand
    from piecrust.formatting.textileformatter import TextileFormatter
  File ".../PieCrust2/piecrust/formatting/textileformatter.py", line 1, in <module>
    from textile import textile
  File ".../PieCrust2/venv/lib/python3.4/site-packages/textile/__init__.py", line 3, in <module>
    from .core import textile, textile_restricted, Textile
  File ".../PieCrust2/venv/lib/python3.4/site-packages/textile/core.py", line 23, in <module>
    import regex
  File ".../PieCrust2/venv/lib/python3.4/site-packages/regex.py", line 673, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File ".../PieCrust2/venv/lib/python3.4/site-packages/regex.py", line 434, in _compile
    pattern_locale = _getlocale()[1]
  File ".../PieCrust2/venv/lib/python3.4/locale.py", line 575, in getlocale
    return _parse_localename(localename)
  File ".../PieCrust2/venv/lib/python3.4/locale.py", line 484, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

**Comment by ludovicchabant** [comment]
Fix with 9d55686bfb460de39db148dbbbfddabfeedc8066, thanks!
