### ISSUE TITLE
"chef init mywebsite" encounter error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [ludovicchabant/PieCrust2#46]
hi.

root@AR:/usr/local/piecrust2-site# chef init mywebsite
Traceback (most recent call last):
  File "/usr/local/bin/chef", line 11, in <module>
    load_entry_point('PieCrust==0.0', 'console_scripts', 'chef')()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-28.8.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-28.8.0-py2.7.egg/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-28.8.0-py2.7.egg/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-28.8.0-py2.7.egg/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/PieCrust-0.0-py2.7.egg/piecrust/main.py", line 201
    raise Exception("Can't write PID file: %s" % res.pid_file) from ex
                                                                  ^
SyntaxError: invalid syntax
root@AR:/usr/local/piecrust2-site#

**Comment by ludovicchabant** [comment]
It looks like you're trying to run PieCrust using a Python 2 environment. You need to do that in a Python 3 environment. Note that you can have Python 2 and 3 installed side by side, they work fine like that.

**Comment by luckypoem** [comment]
hi.

root@AR:/usr/local/piecrust2-site# pip3 install -r requirements.txt
root@AR:/usr/local/piecrust2-site# python3 setup.py install
it shows:
...
Using /usr/local/python-3.5.2/lib/python3.5/site-packages
Finished processing dependencies for PieCrust==0.0
root@AR:/usr/local/piecrust2-site# which chef
/usr/local/python-3.5.2/bin/chef
root@AR:/usr/local/piecrust2-site# chef init piecrust2-blog
root@AR:/usr/local/piecrust2-site# ls piecrust2-blog
config.yml
root@AR:/usr/local/piecrust2-site# 

why in /usr/local/piecrust2-site/piecrust2-blog/,there is ony config.yml and no other stuff?

**Comment by ludovicchabant** [comment]
That's the basic, minimal stuff you need for a website -- just a `config.yml` file. You can create pages and blog posts with `chef prepare page` and `chef prepare post` (or just create text files yourself).

I encourage you to go through the 3-part tutorial here: https://bolt80.com/piecrust/en/latest/getting-started/
